### PR TITLE
#208: Tapiro CI fails because of missing curl (closes #208)

### LINKED ISSUE #208: Tapiro CI fails because of missing curl
Tapiro CI currently fails on `waitIsUp` because it can't run `curl`:
```
[info] [error] java.io.IOException: Cannot run program "curl": error=2, No such file or directory
```

The test runs successfully on my computer.

I suppose it's because `scala-sbt-alpine` doesn't have `curl` (it only installs it temporarily to install `SBT`).

### PR DESCRIPTION
**Pull request by tpetrucciani**
Closes #208

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

File: tapiro/ci/test.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#! /bin/sh
+
+set -e
+
+apk add --no-cache curl
+
+sbt -batch ';tapiroCore/compile ;sbt-tapiro/scripted' # TODO(claudio): compile to test once we have them
```
Comment (gabro) [inline tapiro/ci/test.sh]: I think you either need to add a `cd retro` before this, or use the `dir` option in `run` in the yaml task

Comment (gabro) [reply tapiro/ci/test.sh]: Ah, you were faster than my review :)

Comment (tpetrucciani) [reply tapiro/ci/test.sh]: 👍 looks like it's running now, so the permission should be fine (it was created with permission 755 I think)
