### PR TITLE
#74: Fix parametric types and json codecs names (closes #74)

### LINKED ISSUE #74: Fix parametric types and json codecs names
image

### PR DESCRIPTION
**Pull request by tpetrucciani**
Closes #74

I've changed code generation to replace the use of `typeName` (which gets the name of a Metarpheus type) with a new function `toScalametaType` which instead converts the type back into a Scalameta type. This means that we get parametric types in endpoint types and JSON codecs.

For instance, before this we had:

    val read: Endpoint[Id, BotReadError, BotSummary, Nothing]
    ...
    id: JsonCodec[Id],
    ...
    .out(jsonBody[Id])

and now:

    val read: Endpoint[Id[Bot], BotReadError, BotSummary, Nothing]
    ...
    id: JsonCodec[Id[Bot]],
    ...
    .out(jsonBody[Id[Bot]])

## Test Plan

Continued testing on our internal project, this fixes some compilation errors.

### CODE REVIEW

File: tapiro/core/src/main/scala/io/buildo/tapiro/Cli.scala [hunk 1]
```diff
@@ -36,9 +36,10 @@ object Cli {
 
     OParser.parse(parser, args, CliConfig()) match {
       case Some(c) => {
-        c.`package`.split(".").toList match {
+        c.`package`.split("\\.").toList match {
```
Comment (tpetrucciani) [inline tapiro/core/src/main/scala/io/buildo/tapiro/Cli.scala]: This is unrelated, but I was using the CLI to test and it seems `.` should be escaped here because it's used as a regex

File: tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala [hunk 2]
```diff
@@ -7,17 +7,19 @@ import scala.meta._
...
-    val nameType = Type.Name(name)
-    param"implicit ${paramName}: JsonCodec[$nameType]"
+        errorValues.map(m => MetarpheusType.Name(m.name)) ++
+          route.body.map(_.tpe) :+
+          route.returns
+    }.distinct.map(toImplicitParam)
+
+  private[this] val toImplicitParam = (`type`: MetarpheusType) => {
+    val typeName = typeNameString(`type`)
+    val paramName = Term.Name(s"${typeName.head.toLower}${typeName.tail}")
```
Comment (tpetrucciani) [inline tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala]: I didn't change the parameter name here, so for `Id[Bot]` the parameter name is still `id` (i.e. the type names, first-letter-lowercased, disregarding the arguments).

With this approach we'll definitely run into collisions for routes that take both an `Id[A]` and an `Id[B]`, but I'm not sure what we should do about this.

We could concatenate the type name with the names of the arguments and get `idA`, `idB`, etc...

Alternatively, we could just generate dummy names (`x1`, ...) since I don't think we're actually using these names in the body, we're only using them implicitly...

File: tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala [hunk 3]
```diff
@@ -7,17 +7,19 @@ import scala.meta._
...
-        errorValues.map(_.name) ++
-          route.body.map(b => typeNameString(b.tpe)) :+
-          typeNameString(route.returns)
-    }.distinct.map(stringToImplicitParam)
-
-  private[this] val stringToImplicitParam = (name: String) => {
-    val paramName = Term.Name(s"${name.head.toLower}${name.tail}")
-    val nameType = Type.Name(name)
-    param"implicit ${paramName}: JsonCodec[$nameType]"
+        errorValues.map(m => MetarpheusType.Name(m.name)) ++
```
Comment (tpetrucciani) [inline tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala]: Here we only have the type name and so I'm not using `toScalametaType`. In any case, currently metarpheus doesn't support parametric types as members of tagged unions, so it shouldn't make any difference.

File: tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala (hunk 2 above)
Comment (calippo) [reply tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala]: +1 for dummy names. I propose we open an issue and do that later, handling collisions it's not essential for success of the experiment.
